import type { Metadata } from "next";
import { Plus_Jakarta_Sans as Font, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { AOSInit } from "./utils/AOSInit";

const plusJakartaSans = Font({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={plusJakartaSans.className}>{children}</body>
    </html>
  );
}
